version: '3.9'
services:
  zipkin:
    image: openzipkin/zipkin:2.23.16
    container_name: zipkin
    restart: always
    network_mode: host
    environment:
      - STORAGE_TYPE=elasticsearch
      - STORAGE_PORT_9200_TCP_ADDR="https://65.108.89.131"
      - ES_USERNAME=admin
      - ES_PASSWORD=admin 
      - ES_SSL_NO_VERIFY=true 
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
